//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cs_Message
    {
        public int cm_sid { get; set; }
        public int cu_sid { get; set; }
        public System.DateTime cm_time { get; set; }
        public byte cm_object { get; set; }
        public string cm_desc { get; set; }
        public byte cm_end { get; set; }
    }
}
