//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class good
    {
        public long 商品編號 { get; set; }
        public string 帳號 { get; set; }
        public string 商品名稱 { get; set; }
        public string 商品摘要 { get; set; }
        public string 商品明細 { get; set; }
        public int 庫存量 { get; set; }
        public decimal 單價 { get; set; }
        public System.DateTime 上架時間 { get; set; }
        public System.DateTime 下架時間 { get; set; }
        public string 商品小圖片 { get; set; }
        public string 商品大圖片1 { get; set; }
        public string 商品大圖片2 { get; set; }
        public string 商品大圖片3 { get; set; }
        public string 編輯 { get; set; }
        public int 商品類別代碼 { get; set; }
        public Nullable<bool> 停權 { get; set; }
    }
}
