//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_infro
    {
        public long id { get; set; }
        public string name { get; set; }
        public string nikename { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public Nullable<System.DateTime> birthday_y { get; set; }
        public Nullable<System.DateTime> birthday_m { get; set; }
        public Nullable<System.DateTime> birthday_d { get; set; }
        public Nullable<long> address { get; set; }
    }
}
