//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Gencod { get; set; }
        public long Safe_Stock { get; set; }
        public int Stock { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string pciture { get; set; }
    }
}
