//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingCarEntities : DbContext
    {
        public ShoppingCarEntities()
            : base("name=ShoppingCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cs_Message> Cs_Message { get; set; }
        public virtual DbSet<Cs_User> Cs_User { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<goodstag> goodstags { get; set; }
        public virtual DbSet<leaveAlone> leaveAlones { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<member_ad> member_ad { get; set; }
        public virtual DbSet<member_infro> member_infro { get; set; }
        public virtual DbSet<member_val> member_val { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<shoppingCart> shoppingCarts { get; set; }
        public virtual DbSet<subsite_class> subsite_class { get; set; }
        public virtual DbSet<回覆留言> 回覆留言 { get; set; }
        public virtual DbSet<收貨地址> 收貨地址 { get; set; }
        public virtual DbSet<訂單> 訂單 { get; set; }
        public virtual DbSet<頁面主項> 頁面主項 { get; set; }
        public virtual DbSet<頁面細項> 頁面細項 { get; set; }
        public virtual DbSet<員工使用記錄> 員工使用記錄 { get; set; }
        public virtual DbSet<員工登入資料> 員工登入資料 { get; set; }
        public virtual DbSet<留言版> 留言版 { get; set; }
        public virtual DbSet<郵遞區號> 郵遞區號 { get; set; }
        public virtual DbSet<會員登入記錄> 會員登入記錄 { get; set; }
        public virtual DbSet<縣市> 縣市 { get; set; }
        public virtual DbSet<職稱> 職稱 { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<subsite> subsites { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<訂單明細> 訂單明細 { get; set; }
        public virtual DbSet<員工帳號> 員工帳號 { get; set; }
        public virtual DbSet<員工帳號基本資料> 員工帳號基本資料 { get; set; }
        public virtual DbSet<商品類別> 商品類別 { get; set; }
        public virtual DbSet<帳號使用權限> 帳號使用權限 { get; set; }
        public virtual DbSet<部門> 部門 { get; set; }
        public virtual DbSet<會員> 會員 { get; set; }
        public virtual DbSet<會員住址> 會員住址 { get; set; }
        public virtual DbSet<魔格網站資料> 魔格網站資料 { get; set; }
        public virtual DbSet<權限範圍> 權限範圍 { get; set; }
        public virtual DbSet<FindTodayMenu> FindTodayMenus { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
    
        public virtual ObjectResult<Nullable<int>> IsTodayLunchDone(Nullable<System.DateTime> orderdate)
        {
            var orderdateParameter = orderdate.HasValue ?
                new ObjectParameter("orderdate", orderdate) :
                new ObjectParameter("orderdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IsTodayLunchDone", orderdateParameter);
        }
    
        public virtual int p_Cs_Join(Nullable<int> cu_sid, Nullable<int> mg_sid)
        {
            var cu_sidParameter = cu_sid.HasValue ?
                new ObjectParameter("cu_sid", cu_sid) :
                new ObjectParameter("cu_sid", typeof(int));
    
            var mg_sidParameter = mg_sid.HasValue ?
                new ObjectParameter("mg_sid", mg_sid) :
                new ObjectParameter("mg_sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Cs_Join", cu_sidParameter, mg_sidParameter);
        }
    
        public virtual ObjectResult<ShowAll_Result> ShowAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowAll_Result>("ShowAll");
        }
    
        public virtual ObjectResult<ShowHistory_Result> ShowHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowHistory_Result>("ShowHistory");
        }
    
        public virtual ObjectResult<TodayMenu_Result> TodayMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayMenu_Result>("TodayMenu");
        }
    
        public virtual ObjectResult<TodayOrder_Result> TodayOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayOrder_Result>("TodayOrder");
        }
    
        public virtual ObjectResult<TodayOrderPaid_Result> TodayOrderPaid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayOrderPaid_Result>("TodayOrderPaid");
        }
    
        public virtual ObjectResult<TodayShop_Result> TodayShop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayShop_Result>("TodayShop");
        }
    
        public virtual ObjectResult<Nullable<int>> TotalNumofP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TotalNumofP");
        }
    
        public virtual ObjectResult<TotalOrder_Result> TotalOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalOrder_Result>("TotalOrder");
        }
    
        public virtual ObjectResult<Nullable<int>> TotalPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TotalPrice");
        }
    
        public virtual int UpdateTodayOnduty(Nullable<int> onduty1, Nullable<int> onduty2)
        {
            var onduty1Parameter = onduty1.HasValue ?
                new ObjectParameter("onduty1", onduty1) :
                new ObjectParameter("onduty1", typeof(int));
    
            var onduty2Parameter = onduty2.HasValue ?
                new ObjectParameter("onduty2", onduty2) :
                new ObjectParameter("onduty2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTodayOnduty", onduty1Parameter, onduty2Parameter);
        }
    }
}
