//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 員工使用記錄
    {
        public long 流水號 { get; set; }
        public string 員工帳號 { get; set; }
        public string 操作頁面 { get; set; }
        public string 操作動作 { get; set; }
        public System.DateTime 操作時間 { get; set; }
        public string 備註 { get; set; }
    }
}
