//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 員工帳號基本資料
    {
        public string 員工帳號 { get; set; }
        public string 身份證字號 { get; set; }
        public int 部門代號 { get; set; }
        public int 職稱代號 { get; set; }
        public string 姓名 { get; set; }
        public bool 性別 { get; set; }
        public System.DateTime 出生日期 { get; set; }
        public string email { get; set; }
        public string 聯絡電話 { get; set; }
        public int 郵遞代號 { get; set; }
        public string 地址 { get; set; }
        public bool 在職 { get; set; }
    }
}
