//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 回覆留言
    {
        public int 回覆留言編號 { get; set; }
        public string 回覆內容 { get; set; }
        public System.DateTime 回覆時間 { get; set; }
        public int 留言編號 { get; set; }
    }
}
