//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 會員
    {
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 暱稱 { get; set; }
        public System.DateTime 註冊日期 { get; set; }
        public Nullable<System.DateTime> 啟用日期 { get; set; }
        public Nullable<System.DateTime> 停用日期 { get; set; }
        public bool 啟用 { get; set; }
        public string 其他 { get; set; }
        public bool 性別 { get; set; }
        public string email { get; set; }
        public string 市話 { get; set; }
        public string 手機 { get; set; }
        public System.DateTime 生日 { get; set; }
        public string 權限代碼 { get; set; }
        public bool 認證 { get; set; }
        public System.Guid Validate { get; set; }
    }
}
