//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 郵遞區號
    {
        public int 郵遞代碼 { get; set; }
        public int 郵遞區號1 { get; set; }
        public int 縣市代碼 { get; set; }
        public string 鄉鎮市區 { get; set; }
    }
}
