//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 魔格網站資料
    {
        public System.DateTime 建立日期 { get; set; }
        public string 魔格摘要 { get; set; }
        public string logo圖片路徑 { get; set; }
        public string background圖片路徑 { get; set; }
        public string 廣告圖片路徑 { get; set; }
        public string 員工帳號 { get; set; }
    }
}
